### ISSUE TITLE
Feature Request: Delete action

### ISSUE THREAD

**Issue by kristiandaugaard** [xddesigners/silverstripe-dropzonefield#1]
Would it be possible to create a "delete file"-button, in case of mistaken uploads

**Comment by TheBnl** [comment]
Hi Hoodweb,

Thanks for the suggestion! This is definitely a feature i will want to implement, however it does depends on when i'll have time to implement it.

**Comment by kristiandaugaard** [comment]
Hi Bnl,

Good to know. Currently the only thing holding me back from using the module. I would do a PR if i knew anything about dropzone. But sadly i do not.

Looking forward to a new release in the future :-)

**Comment by TheBnl** [comment]
Took a while but the feature is present as of version 1.2 !
Simply set `$dropzoneField->setAddRemoveLinks(true)` and the remove action will be show and handled by the module.
